# Conclusion

The findings from this data concluded that the distribution of trials is primarily located in larger states where the most amount of medical institutions lie. As well, the most successful trials are the trials with the most amount of patients enrolled and they are the most likely to end in completion. As for each phase of clinical trials, the majority of failure happens in the first two phases and successes are more likely later in the process. The most common form of intervention are drugs with biological products following, although they are almost equally as likely to fail vs. succeed. 

These indications are critical for physicians to be able to provide their patients access to these trials in locations where the trial they are in need of is primarily located. It is helpful for researchers to know where the bottleneck of the clinical trial process lies, and some of the ways to improve completion outcomes (such as increasing enrollment). In the future, it would be beneficial to look at how each cancer type compares across phases and interventions to understand if there are some cancer types or diseases in general that are better or worse in clinical trials. 
