# Data

```{r}
library(dplyr)
library(stringr)
library(ggplot2)
library(tidycensus)
library(tmap)
library(sf)
library(usmap)
```


```{r}
library(choroplethr)
library(dplyr)
library(tidyr)
library(tibble)

breast_cancer <- read.csv("Breast_Cancer.csv", nrows = 197)
breast_cancer_df <- as.data.frame(breast_cancer)

#take out excess columns 
breast_cancer_df <- breast_cancer_df |>
  select(Study.Status:Locations)

#extrapolate states from location
breast_cancer_df <- breast_cancer_df |>
  mutate(
    region = str_extract(
      Locations, "([^,]+),\\s*\\d{5}") |>
    str_replace(",\\s*\\d{5}", "") |>
    str_trim()
  )

# Extrapolate City
breast_cancer_df <- breast_cancer_df %>%
  mutate(
    City = str_split_i(Locations, pattern = ",\\s*", i = 3)
  )
breast_cancer_df$region <- ifelse(breast_cancer_df$region %in% state.name, breast_cancer_df$region, NA)


ggplot(breast_cancer_df, aes(x = region)) +
  geom_bar(fill = "#E91E63") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  labs(title = "Breast Cancer Trials by State (Histogram)",
       x = "State",
       y = "Trial Count")

df_BC_map <- breast_cancer_df |>
  count(region, name = "value")

df_BC_map$value <- cut(df_BC_map$value, breaks = c(0,5,10,15,20,Inf), 
                        labels = c("1-10","6-10","11-15","16-20","20+"), right = TRUE)


state_choropleth(df_BC_map,
                 title = "Breast Cancer Clinical Trials by State",
                 legend = "# of Trials",
                 num_colors = 7) + 
  scale_fill_brewer(palette = "RdPu", 
                    na.value = "grey")
```


```{r}
Top_1000 <- read.csv("Top_1000_Cancers.csv")

#take out excess columns 
Top_1000 <- Top_1000 |>
  select(Study.Status:Locations)

#extrapolate states from location
Top_1000 <- Top_1000 |>
  mutate(
    region = str_extract(
      Locations, "([^,]+),\\s*\\d{5}") |>
    str_replace(",\\s*\\d{5}", "") |>
    str_trim()
  )

# Extrapolate City
Top_1000 <- Top_1000 %>%
  mutate(
    City = str_split_i(Locations, pattern = ",\\s*", i = 3)
  )

Top_1000_map <- Top_1000 |>
  count(region, name = "value")

Top_1000$region <- ifelse(Top_1000$region %in% state.name, Top_1000$region, NA)


ggplot(Top_1000, aes(x = region)) +
  geom_bar(fill = "blue") +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) + 
  labs(title = "Top 1000 Trials by State (Histogram)",
       x = "State",
       y = "Trial Count")

Top_1000_map$value <- cut(
  Top_1000_map$value,
  breaks = c(0, 10, 20, 30, 40, 50, 60, 70, Inf),
  labels = c("1-10", "11-20", "21-30", "31-40", "41-50", "51-60", "61-70", "70+"),
  right = TRUE
)

state_choropleth(Top_1000_map,
                 title = "Top 1000 Cancer Trials by State",
                 legend = "# of Trials",
                 num_colors = 10) + 
  scale_fill_brewer(palette = "Blues",
                    na.value = "grey")

```
```{r}
library(ggalluvial)
Top_1000 <- Top_1000 |>
  mutate(
    Interventions = case_when(
      grepl("^DRUG:", Interventions) ~ "Drug",
      grepl("^GENETIC:", Interventions) ~ "Genetic",
      grepl("^BIOLOGICAL:", Interventions) ~ "Biological",
      grepl("^PROCEDURE:", Interventions) ~ "Procedure",
      grepl("^DEVICE:", Interventions) ~ "Device",
      TRUE ~ "Other" # All non-matching interventions are now grouped and kept
    ),
    Interventions = factor(Interventions)
  )

Top_1000 <- Top_1000 |>
  mutate(
    Study.Status = case_when(
      grepl("^COMPLETED$", Study.Status)   ~ "Completed",
      grepl("^TERMINATED$", Study.Status)  ~ "Terminated",
      TRUE ~ NA_character_
    ),
    Study.Status = factor(Study.Status)
  )

Top_1000$Phases <- factor(Top_1000$Phases, 
                          levels = c("PHASE1", "PHASE2", "PHASE3", "PHASE4", "N/A"))

Top_1000 <- Top_1000 |>
  mutate(
    Phase_Rank = case_when(
      Phases == "NA" ~ NA,
      Phases == "PHASE1" ~ 1,
      Phases == "PHASE2" ~ 2,
      Phases == "PHASE3" ~ 3,
      Phases == "PHASE4" ~ 4
    )
  )

Flow_Phase_Data <- Top_1000 |>
  rowwise() |>
  mutate(
    Phase_1 = ifelse(Phases %in% Phase_Rank[1:4], Phases, NA), 
    Phase_2 = ifelse(Phases %in% Phase_Rank[2:4], Phases, NA), 
    Phase_3 = ifelse(Phases %in% Phase_Rank[3:4], Phases, NA), 
    Phase_4 = ifelse(Phases == "PHASE4", Phases, NA)
)

Flow_Phase_Data <- Flow_Phase_Data |>
  filter(
    !is.na(Interventions),
    !is.na(Phase_Rank),
    !is.na(Study.Status)
  )
```


```{r}
ggplot(Flow_Phase_Data, aes(axis1 = Interventions,
                            axis2 = Phase_Rank,
                            axis3 = Study.Status)) +
  geom_flow(aes(fill = Interventions), width = 1/12) + 
  geom_stratum(width = 1/3, fill = "gray80", color = "black") +
  geom_text(
    stat = "stratum",
    aes(x = after_stat(x),
      y = after_stat(y),
      label = paste(
          after_stat(stratum), "\n", 
          scales::percent(after_stat(count) / nrow(Flow_Phase_Data), accuracy = 0.1))),
      size = 2.5) + 
    scale_x_discrete(limits = c("Intervention", "Phase", "Status"))

  
```

```{r}
library(dplyr)
Top_1000$Enrollment <- as.numeric(Top_1000$Enrollment)

avg_enrollment <- Top_1000 |>
  group_by(Phase_Rank) |>
  summarise(Avg_Enrollment = mean(Enrollment, na.rm = TRUE))

phase_enrollment_avg <- Top_1000 |>
  group_by(Phase_Rank) |>
  summarise(Avg_Enrollment = mean(Enrollment, na.rm = TRUE))

ggplot(avg_enrollment, aes(x = Phase_Rank, y = Avg_Enrollment)) + 
  geom_col(fill = "cornflowerblue") + 
  labs(title = "Average Enrollment by Trial Phase",
       x = "Trial Phase",
       y = "Average Enrollment of Participants") + 
  theme_minimal()

ggplot(
  subset(Top_1000, !is.na(Study.Status)),
  aes(x = Phase_Rank, fill = Study.Status)) +
  geom_bar() + 
  scale_fill_manual(
    values = c(
      "Completed" = "forestgreen",
      "Terminated" = "firebrick")) +
  labs(title = "Completion Status by Trial Phase",
       x = "Trial Phase",
       y = "Frequency")

```


```{r}
## Description

## Missing value analysis
